version: "3.9"
services:
  backend:
    build: ./backend
    image: zephyrus2/backend-xlyzer
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    image: zephyrus2/frontend-xlyzer
    ports:
      - "5173:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
